### ISSUE TITLE
Enable Vulkan backend

### ISSUE THREAD

**Issue by kalyankondapally** [intel/IA-Hardware-Composer#283] opened 2018-03-20 19:54 UTC
@strassek  did most of the work but lot has changed in HWC. We might need to fix any bugs which got introduced into Vulkan backend because of these changes and also make it one of the run time options going forward.

Assigning it to @strassek

**Comment by strassek** [comment] 2018-03-21 23:54
I started to update the Vulkan backend and got it building again. Unfortunately I'm hitting a -EBADF error in drm_gem_prime_fd_to_handle(). It's hard to say where things are going wrong, as the GLES backend takes this same path.

**Comment by strassek** [comment] 2018-03-28 01:15
I ran another test with IAHWC and Mesa sources rolled back to where they were when the Vulkan backend originally landed, and I saw the exact same error. I'll have to try again with a more stable kernel.

**Comment by strassek** [comment] 2018-04-03 21:46
It turns out one of the import issues I was having was cased by a regression in Mesa. I have submitted a patch for that:
https://patchwork.freedesktop.org/patch/214687/

**Closed** 2018-09-13 23:39 UTC
Labels: feature
